@baseUrl = http://localhost:8000
@token = YOUR.TOKEN.HERE

GET {{baseUrl}}/health

###

POST {{baseUrl}}/api/v1/auth/register HTTP/1.1
content-type: application/json

{
    "email": "fake@user.com",
    "password": "verysecret"
}

###

POST {{baseUrl}}/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "docker@test.com",
    "password": "secret123"    
}

###

GET {{baseUrl}}/api/v1/auth/me HTTP/1.1
Authorization: Bearer {{token}}